# Generated by Django 5.2 on 2025-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, default='def.png', upload_to='images/')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Cristian', 'Cristian'), ('Buddho', 'Buddho')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('third', 'third')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('is_Bangladeshi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveBigIntegerField()),
            ],
        ),
    ]
